### ISSUE TITLE
Implement error handling for loss of connection

### ISSUE THREAD

**Issue by samgun-6** [DIT112-V20/group-04#31]
# Description
Introduce error handling mechanism between Android application and SmartCar

# Acceptance criteria:
When connection is lost whilst in manual or voice control the Android application should return to the car selection page

**Comment by krasen86** [comment]
A solution for Error handling when the connection is lost can be pop-up dialog.

**Comment by SandraSmolerEisenberg** [comment]
This issue is not to be implemented due to network connection issues. We are not able to test the feature on a stable router connection since we are testing from a hot spot. Therefore, it was decided that this issue shall be abandoned.
