### ISSUE TITLE
Support Android SDK API version 21(Lollipop) or higher

### ISSUE THREAD

**Issue by SandraSmolerEisenberg** [DIT112-V20/group-04#48]
# User Story: 

- As a developer, I want the system to support Android SDK API version 21(Lollipop) or higher, so that the system can be available to more users.

# Acceptance criteria:
- The system supports Android SDK API version 21(Lollipop) or higher.

**Comment by platisd** [comment]
Isn't this already done?

**Comment by SandraSmolerEisenberg** [comment]
This user story's acceptence critera was met with the "Add basic project structure files" commit in the Wifi-Connectivity milestone (see #20) and tested with Travis CI during sprint 3.
This message closes #48.
