### ISSUE TITLE
Addition of automated tests to the Android application

### ISSUE THREAD

**Issue by chrytsa** [DIT112-V20/group-04#61]
# User Story: 
- As a developer I want to automate my application tests so that I can continuously and confidently deliver a product that works.

# Acceptance criteria:
- All main use cases should have a corresponding automated test.
- Every activity in the application should have automated tests that can verify the main functionality.

**Comment by krasen86** [comment]
There is an issue with how Travis emulator runs instrumented tests for pop-up window. The original version that we tried(see CarSelectTest test_case_3) runs only on local emulators not on Travis CI. We can automate those test to run locally until we find a implementation that works for Travis. Have in mind that your test for pop-up will fail on Travis even if it passes locally.

**Comment by chrytsa** [comment]
The previously mentioned issue is considered to be resolved with [#d93e59e](https://github.com/DIT112-V20/group-04/commit/d93e59e1d6eee18c19db03f182e8927a7011ae2c). As a reference you can look at the respective pull request #77.

**Comment by krasen86** [comment]
After the major logic change when we changed from enums to objects and added database we need to add some more tests for the Car management implementation class. [pull request](https://github.com/DIT112-V20/group-04/pull/86#pullrequestreview-417384033)

**Comment by krasen86** [comment]
After going over the Codecov report we found out that Codecov doesn't take into consideration the unit test and produces code coverage summary based only on the android instrumented test.

**Comment by krasen86** [comment]
We are experiencing timing issues with Travis based on the amount of instrumented test executed on the emulator which take to much time. That is based on the current test environment settings as well as the free Travis version restriction for a build of 50 min. That is why we will not introduce any additional automated test at this point.

**Comment by platisd** [comment]
> After going over the Codecov report we found out that Codecov doesn't take into consideration the unit test and produces code coverage summary based only on the android instrumented test.

You'll have to do a small trick to make codecov combine everything, e.g. take all the coverage reports and place them into a separate folder. We've done something similar with this [script](https://github.com/platisd/indoor-navigation-system/blob/dev/run_coverage.sh).

> That is why we will not introduce any additional automated test at this point.

Why are your instrumented tests taking so long? :scream:

**Comment by krasen86** [comment]
Good question, normally our builds took around 25 - 30min to run all the tests. Once we went over 20 instrumented test the build started to take around 40 min. We need to go over the Travis script and maybe the test set-up logic, what we do before and after each test. I think that currently both the connectedCheck and the connectedAndroidTest in the script execute the tests which slow the build but I'm not sure.
Thanks for the example we'll have a look.

**Comment by platisd** [comment]
No problem. In case you are not doing it already, you may look into parallel `jobs` in Travis which may decrease the overall time.
